image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.10

environment:
  GITHUB_TOKEN:
    secure: Ti46nPnZgFh0nRteU6ma0EhJnCTW7PaMn9hnnewZl4gBFPyRQnXNCwGog02+MRLX

install:
- pip install -r requirements.txt

build_script:
- flet pack app.py --name web-screenshot-maker --icon icon.png --product-name web-screenshot-maker --product-version "1.0" --copyright "Copyright (c) 2022 TrainingData Inc."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a web-screenshot-maker-win.zip %CD%\dist\*.exe

  artifacts:
  - path: web-screenshot-maker-win.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf web-screenshot-maker-macos.tar.gz -C dist web-screenshot-maker.app

  artifacts:
  - path: web-screenshot-maker-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf web-screenshot-maker-linux.tar.gz -C dist web-screenshot-maker

  artifacts:
  - path: web-screenshot-maker-linux.tar.gz
